### ISSUE TITLE
Cant find version 0.5-SNAPSHOT in maven repository

### ISSUE THREAD

**Issue by Anshul21** [danielgerlag/jworkflow#9]
I can't find version 0.5-SNAPSHOT in maven repository. It shows only 0.1-0.3.

https://mvnrepository.com/artifact/net.jworkflow/jworkflow

**Comment by danielgerlag** [comment]
it looks like that page doesn't show any `-SNAPSHOT` versions but they are there

**Comment by maksym-synkevych** [comment]
+1
Can not find pointed version
```
Execution failed for task ':test-app:test-app-impl:compileJava'.
> Could not resolve all files for configuration ':test-app:test-app-impl:compileClasspath'.
   > Could not find net.jworkflow:jworkflow:0.5-SNAPSHOT.
     Required by:
         project :test-app:test-app-impl

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

```

**Comment by quequiere** [comment]
+1 
Can't find 0.5 version 
https://mvnrepository.com/artifact/net.jworkflow/jworkflow

**Comment by nikos** [comment]
@danielgerlag could you please distribute/release the current state (0.5) to maven central?

**Comment by danielgerlag** [comment]
I can see it here - https://oss.sonatype.org/#nexus-search;quick~jworkflow
I don't think mvnrepository.com shows `-SNAPSHOT` releases.

**Comment by nikos** [comment]
Many Thanks, Daniel! It looks like 1.0 is also there 💥

<img width="1256" alt="Bildschirmfoto 2021-01-31 um 11 58 09" src="https://user-images.githubusercontent.com/31314/106381845-e65fbc00-63bb-11eb-834b-d0f22f577b06.png">
